##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qehvcpmt/www/
#    - /bin/cp -R .vscode $DEPLOYPATH
#    - /bin/cp -R assets $DEPLOYPATH
#    - /bin/cp -R css $DEPLOYPATH
#    - /bin/cp -R fonts $DEPLOYPATH
#    - /bin/cp -R img $DEPLOYPATH
#    - /bin/cp -R js $DEPLOYPATH
    index.html $DEPLOYPATH

